= Resumen del Primer Parcial
17100229

=== ¿Qué es HTML y CSS?

HTML es un lenguaje de marcado utilizado para crear páginas en la web, mientras que CSS es un lenguaje utilizado para describir la presentación de un documento tal como son los archivos de HTML

=== ¿Qué es el modelo de caja?
Es el comportamiento que CSS hace hacia todos los elementos del documento HTML, hace que estos se representen mediante cajas rectangulares las cuales se crean automáticamente al escribir una etiqueta HTML. Este tiene distintas propiedades como: content, padding, border, margin y outline

==== Content
Es donde reside el contenido real del elemento, ya sea texto, imagenes, etc.

==== Padding
Es el espacio libre que podemos definir entre el contenido y el borde

==== Border
Es una línea que rodea el padding y el content, ese puede ser cambiado de color o de grosor

==== Margin
Separacion que podemos definir entre la caja y el resto de las cajas existentes

==== Outline
Es una linea que esta rodeando a todo el elemento, incluyendo a los bordes.

=== ¿Qué es la propiedad display?
Es una propiedad con la cual podemos manipular la manera en que mostramos objetos. Este tiene distintos valores como:

==== Block
Hace que el comportamiento del elemento sea el de un bloque

=== Inline
El elemento se mostrará en línea con otros elementos.

=== Inline-block
El elemento tendrá un comportamiento como el de inline y block a la vez

=== None
Desaparece el elemento especificado con este valor.

=== Box-sizing
Esta propiedad nos permite incluir el Padding y Border en el total de Width y Height de un elmento. El valor predeterminado de esta propiedad es content-box, este hace que el padding y border se le sumen al tamaño total del elemento, por lo cual es recomendado utilizar el valor border-box ya que este evita esta situación, separando el padding y border de el tamaño del elemento.

=== ¿Cual es el concepto de flujo de documento?
Los elementos siempre ocupara todo el ancho y alto que se le define, además de que los elementos se apilarán uno arriba del otro

=== Tipos de posicionamiento
Existen distintos tipos de posicionamiento como

* Static

Este es el valor por defecto en CSS, donde el elemento se posiciona segun el flujo normal de la página

* Relative

Se posiciona el elemento de manera personalizada tomando como referencia la posición static del elemento

* Absolute

A diferencia de los anteriores, su posición no estará dentro del flujo normal de la pagina y tomará como referencia el navegador para saber su posición

* Fixed

Este también esta fuera del flujo del documento, este también toma como referencia al navegador para saber su posición, sin embargo siempre mantendrá su posición aunque se le haga scroll a la pagina


=== Unidades de medida utilizadas en CSS

Existen dos tipos de unidades 

* Unidades absolutas

Estos son unidades definidas por lo cual son poco flexibles y no se adaptan fácilmente a las diferentes pantallas, son los siguientes: in (inches), cm (centimetros), mm (milimetros), pt (puntos), pc (picas).

* Unidades relativas

Estas no estan definidas ya que estan referenciando a otros valores. Estas unidades son utilizadas por la flexibilidad con la que se puede adaptar los elementos a la pantalla. Estas son las siguientes unidades: em (respecto al tamaño de letra del elemento), ex (respecto a la altura de la letra 'x' del tipo de letra), px (pixel, respecto a la resolución de la pantalla del dispositivo)

=== Selectores 



=== Pseudoselectores


=== ¿Qué es la cascada?


=== ¿Qué es la especificidad?

