= Resumen del Primer Parcial
17100229

=== ¿Qué es HTML y CSS?

HTML es un lenguaje de marcado utilizado para crear páginas en la web, mientras que CSS es un lenguaje utilizado para describir la presentación de un documento tal como son los archivos de HTML

=== ¿Qué es el modelo de caja?
Es el comportamiento que CSS hace hacia todos los elementos del documento HTML, hace que estos se representen mediante cajas rectangulares las cuales se crean automáticamente al escribir una etiqueta HTML. Este tiene distintas propiedades como: content, padding, border, margin y outline

==== Content
Es donde reside el contenido real del elemento, ya sea texto, imagenes, etc.

==== Padding
Es el espacio libre que podemos definir entre el contenido y el borde

==== Border
Es una línea que rodea el padding y el content, ese puede ser cambiado de color o de grosor

==== Margin
Separacion que podemos definir entre la caja y el resto de las cajas existentes

==== Outline
Es una linea que esta rodeando a todo el elemento, incluyendo a los bordes.

=== ¿Qué es la propiedad display?
Es una propiedad con la cual podemos manipular la manera en que mostramos objetos. Este tiene distintos valores como:

==== Block
Hace que el comportamiento del elemento sea el de un bloque

==== Inline
El elemento se mostrará en línea con otros elementos.

==== Inline-block
El elemento tendrá un comportamiento como el de inline y block a la vez

==== None
Desaparece el elemento especificado con este valor.

==== Box-sizing
Esta propiedad nos permite incluir el Padding y Border en el total de Width y Height de un elmento. El valor predeterminado de esta propiedad es content-box, este hace que el padding y border se le sumen al tamaño total del elemento, por lo cual es recomendado utilizar el valor border-box ya que este evita esta situación, separando el padding y border de el tamaño del elemento.

=== ¿Cual es el concepto de flujo de documento?
Los elementos siempre ocuparan todo el ancho y alto que se le define, además de que los elementos se apilarán uno arriba del otro

=== Tipos de posicionamiento
Existen distintos tipos de posicionamiento como

* Static

Este es el valor por defecto en CSS, donde el elemento se posiciona segun el flujo normal de la página

* Relative

Se posiciona el elemento de manera personalizada tomando como referencia la posición static del elemento

* Absolute

A diferencia de los anteriores, su posición no estará dentro del flujo normal de la pagina y tomará como referencia el navegador para saber su posición

* Fixed

Este también esta fuera del flujo del documento, este también toma como referencia al navegador para saber su posición, sin embargo siempre mantendrá su posición aunque se le haga scroll a la pagina


=== Unidades de medida utilizadas en CSS

Existen dos tipos de unidades 

* Unidades absolutas

Estos son unidades definidas por lo cual son poco flexibles y no se adaptan fácilmente a las diferentes pantallas, son los siguientes: in (inches), cm (centimetros), mm (milimetros), pt (puntos), pc (picas).

* Unidades relativas

Estas no estan definidas ya que estan referenciando a otros valores. Estas unidades son utilizadas por la flexibilidad con la que se puede adaptar los elementos a la pantalla. Estas son las siguientes unidades: em (respecto al tamaño de letra del elemento), ex (respecto a la altura de la letra 'x' del tipo de letra), px (pixel, respecto a la resolución de la pantalla del dispositivo)

=== Selectores 

Son utilizados para dar estilo a elementos especificos, son los existen los selectores básicos como: universal (*)(selecciona todos los elementos de la página), etiqueta (como p) (selecciona todos los elementos que coincidan con la etiqueta), clase (.clase) (Solo da estilo a los elementos determinados con la clase definida), ID (#nombreID) (es igual que los anteriores pero esta vez con un id, utilizado para marcar elemento únicos)

También existen los selectores de relación como: <espacio> (.clase .clase2) (Donde selecciona los elementos .clase2 que sean descendientes de .clase), > (.clase>.clase2)(Donde los elementos .clase2 son hijos de .clase), + (.clase~.clase2) (Donde los elementos .clase2 es el hermano adyacente de .clase), ~ (.clase~.clase2)(Seleciona todos los elementos .clase2 que preceden a .clase).

=== Pseudoselectores

Existen pseudoclases y pseudoselectores

* Pseudoclases

Son utilizados para definir un estado especial de un elemento seleccionado. Por ejemplo

`:hover` Utilizado para cualquier elemento donde el puntero de usuario este sobre el

`:visited` Utilizado para darle estilo a los links que el usuario haya visitado anteriormente 

`:link` Utilizado para darle estilos a los elementos que tengan un atributo `href` que no hayan sido visitados anteriormente por el usuario

`:active` Utilizado para estilizar a un elemento que haya sido activado por el usuario, por ejemplo con un click al elemento.

* Pseudoselectores

Utilizados para seleccionar elementos sin tener que dar el ID o clase de ese elemento, ejemplos:

`:lastchild` Utilizado para seleccionar el ultimo elemento entre un grupo de elementos hermanos

`:last-of-type` Utilizado para seleccionar el ultimo elemento de su tipo 

`:only-child` Utilizado para seleccionar un elemento sin hermanos

=== ¿Qué es la cascada?

CSS analiza por orden tres conceptos para saber que estilos debe de aplicar al documento: importancia (Se determina dependiendo del tipo de las hojas de estilo como Agente de usuario, CSS de usuario y CSS de autor, ademas de el uso de `!important`), especificidad (Sigue un cálculo matemático) y su orden (CSS embebido, CSS interno y CSS externo)

=== ¿Qué es la especificidad?

El navegador lo utiliza para decidir que valores de CSS son más notables para un elemento y estos serán aplicados.
Se calcula utilizando un calculo matematico donde se suman los puntos que tiene un selector

!important (Tiene el mayor puntaje por lo tanto se forzará su utilización)

Etiqueta html (1000 puntos)

ID (100 puntos)

clase, pseudoclase (10 puntos)

elemento, pseudoelemento (1 punto)

Por ejemplo:

`#nav .selected a:hover` tiene la puntuación 121 por que tiene un ID (100), una clase (10), una pseudoclase (10) y un elemento (1)

Existen herramientas en internet como calculadoras para realizar este calculo.